import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full bg-white shadow mb-8">
          <nav className="container mx-auto flex items-center justify-between py-4 px-4">
            <span className="font-bold text-xl">ShadcnUsers</span>
            <div className="space-x-4">
              <a href="/register" className="text-gray-700 hover:underline">
                Kayıt
              </a>
              <a href="/login" className="text-gray-700 hover:underline">
                Giriş
              </a>
              <a href="/profile" className="text-gray-700 hover:underline">
                Profil
              </a>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
